### ISSUE TITLE
Should `read_json()` work when file contents uses single quotes?

### ISSUE THREAD

**Issue by stxue1** [openwdl/wdl#671]
The JSON standard requires double quotes for strings and single quotes are disallowed. However, python tends to output certain values with single quotes. For example:
```python
>>> a = ["hello"]
>>> print(a)
['hello']
>>> import json
>>> json.loads(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
>>> json.loads('["hello"]') # needs to be double quoted
['hello']
```

There is a [unit test](https://github.com/openwdl/wdl/blob/9c0b9cf4586508a9e6260cc5c5e562e21f625aac/SPEC.md?plain=1#L7634-L7657) that depends on this behavior; it tries to take the python stringified output into the `read_json()` standard library function. However, the command section will output `['key1', 'key2']`, which uses single quotes, meaning this is not valid JSON and failing the unit test.

**Comment by claymcleod** [comment]
This was fixed in commit [`afe1eed`](https://github.com/openwdl/wdl/commit/afe1eed) for WDL 1.2+ and commit [`d5fb794`](https://github.com/openwdl/wdl/commit/d5fb794) for WDL 1.1. The fix changed the example to use `json.dump(list(d.keys()), sys.stdout)` instead of `print(list(d.keys()))` to output valid JSON with double quotes.
